### ISSUE TITLE
Kubota passenger extension issues...

### ISSUE THREAD

**Issue by FirenzeIT** [GtX-Andy/easyDevelopmentControls#73] opened 2024-03-05 21:31 UTC
Hello @GtX-Andy, i need contact you for having more issues with the mod in title mentioned, i could send/attach also a videoclip of issue which i have, because without this mod, i don't have this type of errors/problems..

https://app.screencast.com/3fj8kBSpsG2xj

**Comment by GtX-Andy** [comment] 2024-05-04 03:55
Hi,

Sorry for the delayed response I have been busy outside of modding.

I am not 100% sure what your issue is but I think you may be showing me the stutter while driving in cab view. If this is the case i have only had one other player report this problem an unfortunately it is not something I can replicate.

I am not sure how it can be caused by the Passenger Extension as I make no changes to the driver camera or components.
The only things modified is the addition of the passenger seating position and the rest is handled by the Giants DLC especially when you are driving the vehicle.

I am sorry I cannot help with this further at this stage, if I have some free time again soon I will look again to try and discover why a couple people have been affected by this issue and other have not but I cannot promise a solution or answer as it is hard to fix an issue I cannot replicate and I also do have some mods I would like to finish and release first with my free time as I have it 😄 

As this is unrelated I am going to close the issue so there is no confusion, if you need to contact me and you are a member of the Giants Forums you can do so by sending me a PM.. My username is **GtX**. I will reply when I can 👍

**Closed as completed by GtX-Andy** 2024-05-04 03:55 UTC
Labels: unrelated question

**Comment by FirenzeIT** [comment] 2024-05-04 18:24
Hi @GtX-Andy, i tried also today with only passenger extension and tractors of default base game and only 2 others tractors mod, Fendt 1000 and Claas 960 and 1 forage harvest Fend 1050 from MyGameSteam, all the camera shaking such as video below attached... boh!!

https://app.screencast.com/APmYxV09hBm9c

**Comment by DeeDeeRanged** [comment] 2024-07-14 07:24
@FirenzeIT 
What type of hardware are you using, like cpu/videocard, looking closely at your video I can see there are also microstutters outside the cabin.

**Comment by FirenzeIT** [comment] 2024-07-14 10:02
> @FirenzeIT 
> What type of hardware are you using, like cpu/videocard, looking closely at your video I can see there are also microstutters outside the cabin.

I have this type of problems only with Passenger seat mod (kubota passenger extension), and without this not having anything.

INTEL CORE I9 11900K, ASUS ROG STRIX RTX 3090 GAMING OC 24GB (i tried also with 4090, same issues with this mod installed), now without this, not having any stuttering.
